[book]
title = "Język Programowania Rust"
author = "Steve Klabnik oraz Carol Nichols, z udziałem Społeczności Rusta"
language = "pl"

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
